// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: updatePasswordUsers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updatePasswordEmailFromUserID = `-- name: UpdatePasswordEmailFromUserID :exec
update users
set hashed_password = $1, email = $2
where id = $3
`

type UpdatePasswordEmailFromUserIDParams struct {
	HashedPassword string
	Email          string
	ID             uuid.UUID
}

func (q *Queries) UpdatePasswordEmailFromUserID(ctx context.Context, arg UpdatePasswordEmailFromUserIDParams) error {
	_, err := q.db.ExecContext(ctx, updatePasswordEmailFromUserID, arg.HashedPassword, arg.Email, arg.ID)
	return err
}
