// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: updateUserSubWithID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserSubWithID = `-- name: UpdateUserSubWithID :exec
update users
set is_chirpy_red = true
where id = $1
`

func (q *Queries) UpdateUserSubWithID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateUserSubWithID, id)
	return err
}
